version: "3.0"
services:
  db:
    container_name: doctor-order-banco
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=doctor_order_owner
      - POSTGRES_DB=doctor_order
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  api:
    container_name: doctor-order-api
    image: fernandopavan/doctor-order-api:0.1
    ports:
      - 8080:8080
    depends_on:
      - db

  front:
    container_name: doctor-order-front
    image: fernandopavan/doctor-order-front:0.1
    ports:
      - 9000:80
    depends_on:
      - api

volumes:
  db: {}